export type RouteMeta = {
  path: string;
  label?: string;
  hiddenFromMenu?: boolean;
  reason?: string;
  requiredRoles?: string[];
  tenant?: string;
  featureFlag?: string;
};

export const ROUTE_META: RouteMeta[] = [
  { path: "/", label: "Default Landing", hiddenFromMenu: true, reason: "Primary entry route with automatic redirects." },
  { path: "/zone", label: "Marketplace Home", hiddenFromMenu: true, reason: "Primary marketplace entry; access is handled by role/gateway routing and in-page mode controls." },
  { path: "/retail", label: "Legacy Retail Alias", hiddenFromMenu: true, reason: "Legacy alias that redirects to /zone." },
  { path: "/marketplace", label: "Marketplace Home", hiddenFromMenu: true, reason: "Primary marketplace entry; access is handled by role/gateway routing and in-page mode controls." },
  { path: "/about", label: "About", hiddenFromMenu: true, reason: "Marketing page reached from landing flows and contextual links (not part of the admin/agent menus)." },
  { path: "/how-it-works", label: "How It Works", hiddenFromMenu: true, reason: "Marketing page reached from landing flows and contextual links (not part of the admin/agent menus)." },
  { path: "/admin", label: "Admin Login", hiddenFromMenu: true, reason: "Authentication entry screen." },
  { path: "/admin/password", label: "Admin Password Reset", hiddenFromMenu: true, reason: "Password change flow." },
  { path: "/meetings", label: "Meetings Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /ai-team." },
  { path: "/agents", label: "Agents" },
  { path: "/agents/:agentId", label: "Agent Detail", hiddenFromMenu: true, reason: "Detail page linked from Agents home." },
  { path: "/admin/agents", label: "Agent Jobs (Legacy)", hiddenFromMenu: true, reason: "Legacy task runner; daily work is agent-centric under /agents." },
  { path: "/hierarchy", label: "Hierarchy Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /agents." },
  { path: "/whatsapp", label: "WhatsApp Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /admin/communications/whatsapp." },
  { path: "/admin/communications/twilio", label: "Twilio (SMS/WhatsApp)", hiddenFromMenu: true, reason: "Provider control center; daily work is handled via Inbox + agent pages." },
  { path: "/admin/territories", label: "Territories Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /territories." },
  { path: "/admin/territories/:id", label: "Territory Hub Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /territories/:id." },
  { path: "/admin/equipment-ops", label: "Equipment Ops Redirect", hiddenFromMenu: true, reason: "Redirect entry to the default Equipment Ops view." },
  { path: "/admin/wallet", label: "Wallet OS Redirect", hiddenFromMenu: true, reason: "Redirect entry to the default Wallet OS view." },
  { path: "/seller", label: "Seller Dashboard Alias", hiddenFromMenu: true, reason: "Alias route for /seller-dashboard." },
  { path: "/admin/assets/images", label: "Admin Assets Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /admin/media/assets." },
  { path: "/admin/gateway-images", label: "Gateway Images Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /admin/media/assets." },
  { path: "/admin/media/images", label: "Image Studio Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /admin/media/assets." },
  { path: "/admin/website/landing-images", label: "Landing Images Redirect", hiddenFromMenu: true, reason: "Legacy redirect to /admin/media/assets?tab=presets&scope=landing." },
  { path: "/orders/:orderNumber", label: "Order Detail", hiddenFromMenu: true, reason: "Detail page linked from orders list." },
  { path: "/delivery/agent/:id", label: "Delivery Agent Detail", hiddenFromMenu: true, reason: "Detail page linked from delivery admin list." },
  { path: "/territories/:id", label: "Territory Detail", hiddenFromMenu: true, reason: "Detail page linked from territory list." },
  { path: "/contracts/:contractId", label: "Contract Detail", hiddenFromMenu: true, reason: "Detail page linked from contracts list." },
  { path: "/marketplace/sellers/:id", label: "Seller Detail", hiddenFromMenu: true, reason: "Detail page linked from sellers list." },
  { path: "/product/:id", label: "Product Detail", hiddenFromMenu: true, reason: "Detail page linked from marketplace listings." },
  { path: "/verify/:serial", label: "Stamped Gold Verification", hiddenFromMenu: true, reason: "Verification page reached via QR/deep links; not a navigation destination." },
  { path: "/marketplace-old", label: "Legacy Marketplace", hiddenFromMenu: true, reason: "Legacy route kept for backwards compatibility." },
  { path: "/debug/location", label: "Debug Location", hiddenFromMenu: true, reason: "Debug utility, not for production users." },
  { path: "/qa-mobile", label: "QA Mobile Gate", hiddenFromMenu: true, reason: "QA utility, not for production users." },
  { path: "/install", label: "Install App", hiddenFromMenu: true, reason: "Install flow entry (PWA)." },
  { path: "/switch", label: "Switch Space", hiddenFromMenu: true, reason: "Deep link used by space switcher." },
  { path: "/apply/shop", label: "Shop Application", hiddenFromMenu: true, reason: "Application flow entry from CTA." },
  { path: "/apply/delivery", label: "Delivery Application", hiddenFromMenu: true, reason: "Application flow entry from CTA." },
  { path: "/application-status", label: "Application Status", hiddenFromMenu: true, reason: "Status deep link from email." },
  { path: "/cadre-conformite", label: "Compliance", hiddenFromMenu: true, reason: "Legal/compliance footer link." },
  { path: "/terms", label: "Terms", hiddenFromMenu: true, reason: "Legal footer link." },
  { path: "/privacy", label: "Privacy", hiddenFromMenu: true, reason: "Legal footer link." },
  { path: "/login", label: "Login", hiddenFromMenu: true, reason: "Authentication entry screen." },
  { path: "/register", label: "Register", hiddenFromMenu: true, reason: "Authentication entry screen." },
  { path: "/gateway", label: "Gateway", hiddenFromMenu: true, reason: "Primary role gateway entry." },
  { path: "/shop", label: "Marketplace Home", hiddenFromMenu: true, reason: "Marketplace entry handled by CTA/role routing." },
  { path: "/orders", label: "Orders", hiddenFromMenu: true, reason: "Orders view accessed from account/CTA." },
  { path: "/delivery", label: "Delivery Hub", hiddenFromMenu: true, reason: "Delivery hub entry accessed from CTA." },
  { path: "/account", label: "Account", hiddenFromMenu: true, reason: "Account entry accessed from user menu." },
  { path: "/pay/kkiapay/return", label: "Kkiapay Return", hiddenFromMenu: true, reason: "Payment provider return URL." },
  { path: "/wallet/topup/return", label: "Wallet Topup Return", hiddenFromMenu: true, reason: "Top-up provider return URL." },
  { path: "/wallet/topup/flutterwave/return", label: "Flutterwave Return", hiddenFromMenu: true, reason: "Flutterwave wallet top-up return URL." },
  { path: "/pay/flutterwave/return", label: "Flutterwave Pay Return", hiddenFromMenu: true, reason: "Flutterwave payment return URL." },
  { path: "/sellers", label: "Seller Directory", hiddenFromMenu: true, reason: "Directory is accessed from marketplace CTAs and discovery flows." },
  { path: "/seller/topup", label: "Seller Topup", hiddenFromMenu: true, reason: "Topup flow accessed from seller dashboard actions." },
  { path: "/inbox", label: "Inbox", hiddenFromMenu: true, reason: "Conversation hub accessed from contextual entry points (e.g. Wallet strip, buttons, notifications)." },
  { path: "/inbox/:roomKey", label: "Inbox Room", hiddenFromMenu: true, reason: "Conversation room linked from inbox list." },
  { path: "/app/login", label: "Pro App Login", hiddenFromMenu: true, reason: "Professional app entry; accessed via deep links/CTA." },
  { path: "/app/join/:role", label: "Pro App Join", hiddenFromMenu: true, reason: "Professional app onboarding flow." },
  { path: "/app", label: "Pro App", hiddenFromMenu: true, reason: "Professional app home; entry is role-driven." },
  { path: "/app/room/:roomKey", label: "Pro App Room", hiddenFromMenu: true, reason: "Professional app conversation room linked from pro inbox." },
  { path: "/app/equipment", label: "Pro App Equipment", hiddenFromMenu: true, reason: "Professional equipment tools accessed from the pro app." },
  { path: "/app/:rest*", label: "Pro App Redirect", hiddenFromMenu: true, reason: "Catch-all redirect for professional app deep links." },
];
