FROM node:20-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
ARG BUILD_ID
ARG GIT_SHA
ARG APP_NAME
ARG TENANT_DEFAULT
ARG DEPLOY_TENANT
ARG PUBLIC_BASE_URL
ARG APP_BASE_URL
ARG PASSWORD_SETUP_BASE_URL
ENV BUILD_ID=$BUILD_ID
ENV GIT_SHA=$GIT_SHA
ENV APP_NAME=$APP_NAME
ENV TENANT_DEFAULT=$TENANT_DEFAULT
ENV DEPLOY_TENANT=$DEPLOY_TENANT
ENV PUBLIC_BASE_URL=$PUBLIC_BASE_URL
ENV APP_BASE_URL=$APP_BASE_URL
ENV PASSWORD_SETUP_BASE_URL=$PASSWORD_SETUP_BASE_URL
ENV SKIP_MARKETING_QUALITY_GATE=1
COPY . .
RUN npm run build

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ARG BUILD_ID
ARG GIT_SHA
ARG APP_NAME
ARG TENANT_DEFAULT
ARG DEPLOY_TENANT
ARG PUBLIC_BASE_URL
ARG APP_BASE_URL
ARG PASSWORD_SETUP_BASE_URL
ENV BUILD_ID=$BUILD_ID
ENV GIT_SHA=$GIT_SHA
ENV APP_NAME=$APP_NAME
ENV TENANT_DEFAULT=$TENANT_DEFAULT
ENV DEPLOY_TENANT=$DEPLOY_TENANT
ENV PUBLIC_BASE_URL=$PUBLIC_BASE_URL
ENV APP_BASE_URL=$APP_BASE_URL
ENV PASSWORD_SETUP_BASE_URL=$PASSWORD_SETUP_BASE_URL

COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json package-lock.json tsconfig.json env.ts ./
COPY db ./db
COPY server ./server
COPY scripts ./scripts
COPY client/src/App.tsx ./client/src/App.tsx

RUN mkdir -p /app/attached_assets
EXPOSE 5000
CMD ["node", "dist/index.js"]
