# ------------------------------------------------------------
# zogueland.com, www.zogueland.com
# ------------------------------------------------------------

server {
  set $forward_scheme http;
  set $server         bdo-app;
  set $port           5000;

  listen 80;
  listen [::]:80;

  listen 443 ssl;
  listen [::]:443 ssl;

  server_name zogueland.com www.zogueland.com;

  http2 on;

  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-cache.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/zogueland.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/zogueland.com/privkey.pem;

  include conf.d/include/block-exploits.conf;
  include conf.d/include/force-ssl.conf;

  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  proxy_http_version 1.1;

  access_log /data/logs/proxy-host-14_access.log proxy;
  error_log /data/logs/proxy-host-14_error.log warn;

  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    include conf.d/include/proxy.conf;
  }

  include /data/nginx/custom/server_proxy[.]conf;
}
