export const ENGINEERING_SOURCE = {
  workbookName: "Electric Vehicle Team .xlsx",
  workbookSha256: "e660821463628fa00f087144b928e0ed7863d0a8444c7d4baa8b297519a2114b",
  communicationsDocumentId: "1bBVpJhJZ1cerxQcBwL_VYfXwYZk8v98N",
  communicationsDocumentUrl:
    "https://docs.google.com/document/d/1bBVpJhJZ1cerxQcBwL_VYfXwYZk8v98N/edit",
  importedAt: "2026-07-28",
} as const;

export const ENGINEERING_TEAM_SLUGS = {
  cad: "ingenierie-cad-mecanique",
  electrical: "ingenierie-electrique-pcb",
  firmware: "ingenierie-firmware-embarque",
  software: "ingenierie-logiciel-interface",
  integration: "ingenierie-integration-securite",
} as const;

export type EngineeringTeamSlug =
  (typeof ENGINEERING_TEAM_SLUGS)[keyof typeof ENGINEERING_TEAM_SLUGS];

export const ENGINEERING_TEAMS: ReadonlyArray<{
  slug: EngineeringTeamSlug;
  name: string;
  mission: string;
  channelSlug: string;
  channelName: string;
}> = [
  {
    slug: ENGINEERING_TEAM_SLUGS.cad,
    name: "CAD & mécanique",
    mission: "Concevoir le châssis, la carrosserie, les supports, les sièges et l'intégration mécanique.",
    channelSlug: "ingenierie-cad-mecanique",
    channelName: "CAD & mécanique",
  },
  {
    slug: ENGINEERING_TEAM_SLUGS.electrical,
    name: "Électricité, simulation & PCB",
    mission: "Dimensionner, simuler, câbler et tester les sous-systèmes électriques basse et haute tension.",
    channelSlug: "ingenierie-electrique-pcb",
    channelName: "Électricité, simulation & PCB",
  },
  {
    slug: ENGINEERING_TEAM_SLUGS.firmware,
    name: "Firmware & systèmes embarqués",
    mission: "Développer le firmware, le CAN, le monitoring, les alertes et les équipements embarqués.",
    channelSlug: "ingenierie-firmware-embarque",
    channelName: "Firmware & embarqué",
  },
  {
    slug: ENGINEERING_TEAM_SLUGS.software,
    name: "Logiciel embarqué & interface",
    mission: "Construire l'interface conducteur, le mode hors connexion, la synchronisation et les interactions.",
    channelSlug: "ingenierie-logiciel-interface",
    channelName: "Logiciel & interface",
  },
  {
    slug: ENGINEERING_TEAM_SLUGS.integration,
    name: "Intégration, essais & sécurité",
    mission: "Assembler les sous-systèmes, organiser les essais, traiter les défauts et valider la sécurité.",
    channelSlug: "ingenierie-integration-securite",
    channelName: "Intégration, essais & sécurité",
  },
] as const;

export type NdaStatus = "signed" | "not_recorded";
export type AssignmentConfidence = "source" | "inferred_needs_confirmation";

export type EngineeringRosterMember = {
  sourceUid: string;
  sourceRows: number[];
  sourceName: string;
  firstName: string;
  lastName: string;
  displayName: string;
  corporateLocalPart: string;
  corporateEmail: string;
  personalEmail: string | null;
  personalEmailRecorded: boolean;
  phone: string | null;
  studyProgram: string | null;
  sourceSquad: string | null;
  teamSlug: EngineeringTeamSlug;
  roleTitle: string;
  skills: string[];
  assignmentConfidence: AssignmentConfidence;
  ndaStatus: NdaStatus;
  ndaUrl: string | null;
};

type RosterInput = Omit<
  EngineeringRosterMember,
  "sourceUid" | "corporateEmail" | "displayName" | "personalEmailRecorded"
>;

function member(input: RosterInput): EngineeringRosterMember {
  const firstName = input.firstName.trim();
  const lastName = input.lastName.trim();
  const localPart = input.corporateLocalPart
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, "")
    .replace(/^\.+|\.+$/g, "");
  return {
    ...input,
    sourceUid: `electric-vehicle-team:${input.sourceRows.join("+")}`,
    firstName,
    lastName,
    displayName: `${firstName} ${lastName}`.trim(),
    corporateLocalPart: localPart,
    corporateEmail: `${localPart}@agoojiye.com`,
    personalEmail: input.personalEmail?.trim().toLowerCase() || null,
    personalEmailRecorded: !input.sourceRows.some((row) => row === 8 || row === 15),
    phone: input.phone?.trim() || null,
    studyProgram: input.studyProgram?.trim() || null,
    sourceSquad: input.sourceSquad?.trim() || null,
  };
}

const CAD_ROLE = "Ingénieur conception mécanique (CAD)";
const ELECTRICAL_ROLE = "Ingénieur électricité, simulation & PCB";
const FIRMWARE_ROLE = "Ingénieur firmware & systèmes embarqués";
const SOFTWARE_ROLE = "Ingénieur logiciel embarqué & interface";
const UNCONFIRMED_ROLE = "Ingénieur - spécialité à confirmer";

export const ENGINEERING_ROSTER: ReadonlyArray<EngineeringRosterMember> = [
  member({
    sourceRows: [3],
    sourceName: "BAKPE Gismano Somako Espero",
    firstName: "Gismano",
    lastName: "BAKPE",
    corporateLocalPart: "gismano",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD", "Conception mécanique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [4],
    sourceName: "GOKOU Hadodile Azanma",
    firstName: "Hadodile",
    lastName: "GOKOU",
    corporateLocalPart: "hadodile",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB/Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB", "Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [5],
    sourceName: "OKE Donald Riquelme D.",
    firstName: "Donald",
    lastName: "OKE",
    corporateLocalPart: "donald",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [6, 36],
    sourceName: "GBAGUIDI Judicaël Odilon Moulero",
    firstName: "Judicaël",
    lastName: "GBAGUIDI",
    corporateLocalPart: "judicael",
    personalEmail: null,
    phone: null,
    studyProgram: "Ingénieur Génie Informatique et Télécommunications",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Télécommunications"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [7],
    sourceName: "AVOCETIEN Issac",
    firstName: "Issac",
    lastName: "AVOCETIEN",
    corporateLocalPart: "isaac",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB / Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB", "Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [8],
    sourceName: "BOCOVO Fried L. E.",
    firstName: "Fried",
    lastName: "BOCOVO",
    corporateLocalPart: "fried",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: null,
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    roleTitle: UNCONFIRMED_ROLE,
    skills: ["Intégration"],
    assignmentConfidence: "inferred_needs_confirmation",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [9],
    sourceName: "AKPATA Gbètondji Serge",
    firstName: "Serge",
    lastName: "AKPATA",
    corporateLocalPart: "serge",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie mécanique",
    sourceSquad: "Simulation & PCB",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB", "Génie mécanique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [10],
    sourceName: "EGOUDJOBI Peace Fiacre",
    firstName: "Peace",
    lastName: "EGOUDJOBI",
    corporateLocalPart: "peace",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: null,
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    roleTitle: UNCONFIRMED_ROLE,
    skills: ["Intégration"],
    assignmentConfidence: "inferred_needs_confirmation",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [11],
    sourceName: "ALONOUMI Z. C. Bosco",
    firstName: "Bosco",
    lastName: "ALONOUMI",
    corporateLocalPart: "bosco",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie informatique",
    sourceSquad: "Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    roleTitle: FIRMWARE_ROLE,
    skills: ["Firmware", "Génie informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [12],
    sourceName: "KOSSOUHO Fourier Mermoz Bignon Kakpo",
    firstName: "Fourier",
    lastName: "KOSSOUHO",
    corporateLocalPart: "fourier",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB / Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB", "Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [13],
    sourceName: "DJEGBO Géoffroy",
    firstName: "Géoffroy",
    lastName: "DJEGBO",
    corporateLocalPart: "geoffroy",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie mécanique",
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD", "Génie mécanique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [14],
    sourceName: "GNANSOUNOU Auriol Kundé Sylvanus",
    firstName: "Auriol",
    lastName: "GNANSOUNOU",
    corporateLocalPart: "auriol",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB / Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB", "Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [15],
    sourceName: "ATCHIN PRINCE",
    firstName: "Prince",
    lastName: "ATCHIN",
    corporateLocalPart: "prince",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: null,
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    roleTitle: UNCONFIRMED_ROLE,
    skills: ["Intégration"],
    assignmentConfidence: "inferred_needs_confirmation",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [16],
    sourceName: "Vincent Dotou MEVOWANOU",
    firstName: "Vincent",
    lastName: "MEVOWANOU",
    corporateLocalPart: "vincent",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie mécanique",
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD", "Génie mécanique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [17],
    sourceName: "DJEDJE Aldo",
    firstName: "Aldo",
    lastName: "DJEDJE",
    corporateLocalPart: "aldo",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [18],
    sourceName: "KPODEGBE Evodie",
    firstName: "Evodie",
    lastName: "KPODEGBE",
    corporateLocalPart: "evodie",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Simulation & PCB",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    roleTitle: ELECTRICAL_ROLE,
    skills: ["Simulation", "PCB"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [19],
    sourceName: "Sunday KPOKPO",
    firstName: "Sunday",
    lastName: "KPOKPO",
    corporateLocalPart: "sunday",
    personalEmail: null,
    phone: null,
    studyProgram: "Génie électrique",
    sourceSquad: "Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    roleTitle: FIRMWARE_ROLE,
    skills: ["Firmware", "Génie électrique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [20],
    sourceName: "COMLAN Ifè Léonce",
    firstName: "Léonce",
    lastName: "COMLAN",
    corporateLocalPart: "leonce",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    roleTitle: FIRMWARE_ROLE,
    skills: ["Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [21],
    sourceName: "GOUDJINOU Marc-Aurel",
    firstName: "Marc-Aurel",
    lastName: "GOUDJINOU",
    corporateLocalPart: "marc-aurel",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [22],
    sourceName: "TOSSOU Sèyidè Mélaine",
    firstName: "Mélaine",
    lastName: "TOSSOU",
    corporateLocalPart: "melaine",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [23],
    sourceName: "AGOSSOU Consolé",
    firstName: "Consolé",
    lastName: "AGOSSOU",
    corporateLocalPart: "console",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [24],
    sourceName: "HOUEDJISSIN Mahougnon Josaphat",
    firstName: "Josaphat",
    lastName: "HOUEDJISSIN",
    corporateLocalPart: "josaphat",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "CAD",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    roleTitle: CAD_ROLE,
    skills: ["CAD"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [25],
    sourceName: "AVLESSI Fleurette",
    firstName: "Fleurette",
    lastName: "AVLESSI",
    corporateLocalPart: "fleurette",
    personalEmail: null,
    phone: null,
    studyProgram: null,
    sourceSquad: "Firmware",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    roleTitle: FIRMWARE_ROLE,
    skills: ["Firmware"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
  member({
    sourceRows: [26],
    sourceName: "AGBECI David",
    firstName: "David",
    lastName: "AGBECI",
    corporateLocalPart: "david.agbeci",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [27],
    sourceName: "Theophore BONOU",
    firstName: "Theophore",
    lastName: "BONOU",
    corporateLocalPart: "theophore",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [28],
    sourceName: "Alexis ASSOGBA",
    firstName: "Alexis",
    lastName: "ASSOGBA",
    corporateLocalPart: "alexis",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [29],
    sourceName: "Angelo FANOU",
    firstName: "Angelo",
    lastName: "FANOU",
    corporateLocalPart: "angelo",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [30],
    sourceName: "Mohamed ALASSANE",
    firstName: "Mohamed",
    lastName: "ALASSANE",
    corporateLocalPart: "mohamed",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [31],
    sourceName: "GBAGUIDI Jordy",
    firstName: "Jordy",
    lastName: "GBAGUIDI",
    corporateLocalPart: "jordy",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [32],
    sourceName: "KPODOHOUN Horus",
    firstName: "Horus",
    lastName: "KPODOHOUN",
    corporateLocalPart: "horus",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [33],
    sourceName: "David TCHEGNIMONHAN",
    firstName: "David",
    lastName: "TCHEGNIMONHAN",
    corporateLocalPart: "david.tchegnimonhan",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [34],
    sourceName: "Delor DAH-GUEDENON",
    firstName: "Delor",
    lastName: "DAH-GUEDENON",
    corporateLocalPart: "delor",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [35],
    sourceName: "Ange ADANTCHEDE",
    firstName: "Ange",
    lastName: "ADANTCHEDE",
    corporateLocalPart: "ange",
    personalEmail: null,
    phone: null,
    studyProgram: "Système informatique",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Système informatique"],
    assignmentConfidence: "source",
    ndaStatus: "signed",
    ndaUrl: null,
  }),
  member({
    sourceRows: [37],
    sourceName: "MEDENOU Gilles",
    firstName: "Gilles",
    lastName: "MEDENOU",
    corporateLocalPart: "gilles",
    personalEmail: null,
    phone: null,
    studyProgram: "Ingénieur Génie Informatique et Télécommunications",
    sourceSquad: "Frontend/UI",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    roleTitle: SOFTWARE_ROLE,
    skills: ["Frontend", "UI", "Télécommunications"],
    assignmentConfidence: "source",
    ndaStatus: "not_recorded",
    ndaUrl: null,
  }),
] as const;

export const ENGINEERING_MILESTONES = [
  { id: "s1-chassis", name: "S1 - Châssis fabriqué", dueAt: "2026-07-31T17:00:00+01:00", status: "planned" },
  { id: "s2-subsystems", name: "S2 - Sous-systèmes, supports et sièges prêts", dueAt: "2026-08-07T17:00:00+01:00", status: "planned" },
  { id: "s3-integration", name: "S3 - Intégration système et carrosserie prêtes", dueAt: "2026-08-14T17:00:00+01:00", status: "planned" },
  { id: "s4-first-roll", name: "S4 - Assemblage complet et premier roulage", dueAt: "2026-08-21T17:00:00+01:00", status: "planned" },
  { id: "s5-safety", name: "S5 - Rapport fiabilité et protocole sécurité", dueAt: "2026-08-28T17:00:00+01:00", status: "planned" },
  { id: "s6-prototype", name: "S6 - Prototype et documentation prêts", dueAt: "2026-09-04T17:00:00+01:00", status: "planned" },
] as const;

export type EngineeringTaskSeed = {
  key: string;
  title: string;
  description: string;
  teamSlug: EngineeringTeamSlug | "communication-media";
  priority: "critical" | "high" | "medium";
  dueAt: string;
  phase: string;
  checklist: string[];
};

export const ENGINEERING_TASKS: ReadonlyArray<EngineeringTaskSeed> = [
  {
    key: "s1-chassis",
    title: "Fabriquer le châssis du prototype",
    description: "Découpe, soudure et usinage du châssis à la SIAB.",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    priority: "critical",
    dueAt: "2026-07-31T17:00:00+01:00",
    phase: "S1",
    checklist: ["Découpe terminée", "Soudure contrôlée", "Usinage terminé", "Contrôle dimensionnel documenté"],
  },
  {
    key: "s2-battery-bms",
    title: "Assembler le pack batterie et le BMS",
    description: "Assembler et contrôler le pack batterie, le BMS et les protections associées à l'EPAC.",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    priority: "critical",
    dueAt: "2026-08-07T17:00:00+01:00",
    phase: "S2",
    checklist: ["Architecture validée", "Pack assemblé", "BMS configuré", "Mesures consignées"],
  },
  {
    key: "s2-hv-lv-wiring",
    title: "Réaliser le câblage haute et basse tension",
    description: "Câbler les boucles HT et BT avec repérage, isolation et contrôles de continuité.",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    priority: "critical",
    dueAt: "2026-08-07T17:00:00+01:00",
    phase: "S2",
    checklist: ["Schéma à jour", "Câbles repérés", "Continuité contrôlée", "Isolation contrôlée"],
  },
  {
    key: "s2-subsystem-tests",
    title: "Tester individuellement les sous-systèmes",
    description: "Vérifier chaque sous-système avant l'intégration globale et consigner les résultats.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "high",
    dueAt: "2026-08-07T17:00:00+01:00",
    phase: "S2",
    checklist: ["Plan de test", "Résultats électriques", "Résultats firmware", "Anomalies enregistrées"],
  },
  {
    key: "s2-seat-supports",
    title: "Construire les supports de sièges",
    description: "Découpe, soudure et usinage des supports de sièges à la SIAB.",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    priority: "high",
    dueAt: "2026-08-07T17:00:00+01:00",
    phase: "S2",
    checklist: ["Dimensions validées", "Supports fabriqués", "Fixations contrôlées"],
  },
  {
    key: "s2-seats",
    title: "Suivre la fabrication des sièges",
    description: "Coordonner le tissu, le rembourrage, l'armature et les fixations avec le matelassier.",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    priority: "high",
    dueAt: "2026-08-07T17:00:00+01:00",
    phase: "S2",
    checklist: ["Point mi-semaine effectué", "Armatures prêtes", "Rembourrage terminé", "Sièges réceptionnés"],
  },
  {
    key: "s3-offline-sync",
    title: "Finaliser le mode hors connexion et la synchronisation",
    description: "Garantir la continuité de l'interface embarquée sans réseau et la reprise de synchronisation.",
    teamSlug: ENGINEERING_TEAM_SLUGS.software,
    priority: "critical",
    dueAt: "2026-08-12T17:00:00+01:00",
    phase: "S3",
    checklist: ["Scénarios hors ligne", "File de synchronisation", "Reprise réseau", "Journal de test"],
  },
  {
    key: "s3-audio-interactions",
    title: "Intégrer les annonces audio et les interactions",
    description: "Tester la diffusion d'annonces et les interactions vocales et textuelles.",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    priority: "high",
    dueAt: "2026-08-12T17:00:00+01:00",
    phase: "S3",
    checklist: ["Annonces audio", "Interaction vocale", "Interaction textuelle", "Mode dégradé"],
  },
  {
    key: "s3-monitoring",
    title: "Rendre le monitoring batterie et vitesse opérationnel",
    description: "Afficher et enregistrer en temps réel les données utiles du véhicule.",
    teamSlug: ENGINEERING_TEAM_SLUGS.firmware,
    priority: "critical",
    dueAt: "2026-08-12T17:00:00+01:00",
    phase: "S3",
    checklist: ["Lecture CAN", "Batterie affichée", "Vitesse affichée", "Logs SSD"],
  },
  {
    key: "s3-safety-alerts",
    title: "Valider les alertes de sécurité",
    description: "Tester les alertes de surchauffe, basse tension, isolement et défaut de boucle.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "critical",
    dueAt: "2026-08-12T17:00:00+01:00",
    phase: "S3",
    checklist: ["Surchauffe", "Basse tension", "Défaut d'isolement", "Défaut HVIL"],
  },
  {
    key: "s3-integration-tests",
    title: "Exécuter les tests unitaires et d'intégration globale",
    description: "Consolider les preuves de test à l'EPAC et à l'UNIPOD.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "critical",
    dueAt: "2026-08-14T17:00:00+01:00",
    phase: "S3",
    checklist: ["Tests unitaires", "Tests d'interface", "Tests d'intégration", "Anomalies priorisées"],
  },
  {
    key: "s3-bodywork",
    title: "Livrer la carrosserie du prototype",
    description: "Découpe, soudure et usinage de la carrosserie à la SIAB, avec livraison cible le 12 août.",
    teamSlug: ENGINEERING_TEAM_SLUGS.cad,
    priority: "critical",
    dueAt: "2026-08-12T17:00:00+01:00",
    phase: "S3",
    checklist: ["Structure terminée", "Dimensions contrôlées", "Carrosserie livrée"],
  },
  {
    key: "s4-final-assembly",
    title: "Réaliser l'assemblage final et le premier roulage",
    description: "Assembler le véhicule complet, effectuer la mise en route et documenter le premier roulage à la GDIZ.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "critical",
    dueAt: "2026-08-21T17:00:00+01:00",
    phase: "S4",
    checklist: ["Assemblage mécanique", "Assemblage électrique", "Mise en route", "Premier roulage documenté"],
  },
  {
    key: "s5-reliability-safety",
    title: "Mener les essais de fiabilité et de sécurité",
    description: "Exécuter les essais intensifs, corriger les défauts et valider le protocole de sécurité.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "critical",
    dueAt: "2026-08-28T17:00:00+01:00",
    phase: "S5",
    checklist: ["Campagne d'essais", "Défauts classés", "Corrections vérifiées", "Rapport signé"],
  },
  {
    key: "s6-final-documentation",
    title: "Finaliser le prototype et sa documentation",
    description: "Geler la configuration présentée, consolider les schémas, essais, limites et procédures.",
    teamSlug: ENGINEERING_TEAM_SLUGS.integration,
    priority: "critical",
    dueAt: "2026-09-04T17:00:00+01:00",
    phase: "S6",
    checklist: ["Configuration gelée", "Dossier technique", "Dossier sécurité", "Guide d'exploitation"],
  },
  {
    key: "component-register",
    title: "Compléter le registre des composants",
    description: "Renseigner quantité, coût estimatif, source d'achat, responsable et statut de chaque composant.",
    teamSlug: ENGINEERING_TEAM_SLUGS.electrical,
    priority: "high",
    dueAt: "2026-08-03T17:00:00+01:00",
    phase: "Transverse",
    checklist: ["Quantités", "Coûts estimatifs", "Liens d'achat", "Responsables", "Statuts d'approvisionnement"],
  },
] as const;

export const LAUNCH_COMMUNICATION_TASKS: ReadonlyArray<EngineeringTaskSeed> = [
  {
    key: "launch-teasing",
    title: "Campagne lancement - Teasing",
    description: "Préparer les premiers contenus et stories de la campagne AGOOJIYE.",
    teamSlug: "communication-media",
    priority: "high",
    dueAt: "2026-08-03T17:00:00+01:00",
    phase: "Teasing",
    checklist: ["Post principal", "Stories", "Actifs validés"],
  },
  {
    key: "launch-builders",
    title: "Campagne lancement - Builders",
    description: "Présenter les équipes et les personnes qui construisent le prototype.",
    teamSlug: "communication-media",
    priority: "high",
    dueAt: "2026-08-10T17:00:00+01:00",
    phase: "Builders",
    checklist: ["Portraits", "Captions", "Validation équipe"],
  },
  {
    key: "launch-construction",
    title: "Campagne lancement - Construction",
    description: "Documenter la progression réelle du prototype sans divulguer les informations restreintes.",
    teamSlug: "communication-media",
    priority: "high",
    dueAt: "2026-08-17T17:00:00+01:00",
    phase: "Construction",
    checklist: ["Images chantier", "Reel", "Validation confidentialité"],
  },
  {
    key: "launch-hype",
    title: "Campagne lancement - Hype",
    description: "Préparer la montée en puissance avant la présentation.",
    teamSlug: "communication-media",
    priority: "high",
    dueAt: "2026-08-24T17:00:00+01:00",
    phase: "Hype",
    checklist: ["Compte à rebours", "Stories", "Relais partenaires"],
  },
  {
    key: "launch-gala",
    title: "Campagne lancement - Gala sponsors",
    description: "Préparer la couverture en direct et les contenus de présentation officielle.",
    teamSlug: "communication-media",
    priority: "critical",
    dueAt: "2026-08-31T17:00:00+01:00",
    phase: "Gala",
    checklist: ["Conducteur live", "Captation", "Presse", "Partenaires"],
  },
  {
    key: "launch-finale",
    title: "Campagne lancement - Amplification et finale",
    description: "Publier les résultats, remerciements et prochaines étapes après la présentation.",
    teamSlug: "communication-media",
    priority: "high",
    dueAt: "2026-09-04T17:00:00+01:00",
    phase: "Amplification",
    checklist: ["Récapitulatif", "Remerciements", "Prochaines étapes"],
  },
] as const;

export const ENGINEERING_COMPONENTS = {
  dashboard: [
    "Raspberry Pi 4",
    "PiCAN 2 (MCP2515)",
    "Écran 10,1 pouces 1280x800",
    "Stockage SSD USB",
    "Carte d'équilibrage supercondensateurs 2,7 V / 10 F",
    "Diode et résistance de précharge du banc",
    "Convertisseur DC-DC step-down 5 V / 5 A",
  ],
  highVoltageTraction: [
    "Pack batterie de traction",
    "BMS",
    "PDU",
    "Contacteur principal HT",
    "Contacteur de précharge",
    "Résistance de précharge",
    "Fusible HT",
    "MSD",
    "Onduleur / contrôleur moteur",
    "Moteur électrique",
    "Réducteur",
    "Différentiel",
    "Demi-arbres et joints homocinétiques",
    "Câbles HT orange blindés",
    "Contrôleur d'isolement IMD",
    "Boucle HVIL",
  ],
} as const;

export const ENGINEERING_MEETINGS = [
  { key: "weekly-s1", title: "Point ingénierie - S1 châssis", startsAt: "2026-07-29T08:30:00+01:00", endsAt: "2026-07-29T09:15:00+01:00" },
  { key: "weekly-s2", title: "Point ingénierie - S2 sous-systèmes", startsAt: "2026-08-03T08:30:00+01:00", endsAt: "2026-08-03T09:15:00+01:00" },
  { key: "seat-check", title: "Point mi-semaine - fabrication des sièges", startsAt: "2026-08-05T15:00:00+01:00", endsAt: "2026-08-05T15:30:00+01:00" },
  { key: "integration-gate", title: "Revue d'intégration système", startsAt: "2026-08-12T15:00:00+01:00", endsAt: "2026-08-12T16:00:00+01:00" },
  { key: "first-roll", title: "Revue premier roulage", startsAt: "2026-08-21T15:00:00+01:00", endsAt: "2026-08-21T16:00:00+01:00" },
  { key: "safety-review", title: "Revue fiabilité et sécurité", startsAt: "2026-08-28T15:00:00+01:00", endsAt: "2026-08-28T16:00:00+01:00" },
  { key: "final-readiness", title: "Revue finale prototype", startsAt: "2026-09-04T10:00:00+01:00", endsAt: "2026-09-04T11:00:00+01:00" },
] as const;

export function summarizeEngineeringRoster(roster = ENGINEERING_ROSTER) {
  const byTeam = Object.fromEntries(
    ENGINEERING_TEAMS.map((team) => [team.slug, roster.filter((entry) => entry.teamSlug === team.slug).length]),
  ) as Record<EngineeringTeamSlug, number>;
  return {
    total: roster.length,
    byTeam,
    missingPersonalEmail: roster.filter((entry) => !entry.personalEmailRecorded).length,
    ndaSigned: roster.filter((entry) => entry.ndaStatus === "signed").length,
    ndaNotRecorded: roster.filter((entry) => entry.ndaStatus === "not_recorded").length,
    assignmentsToConfirm: roster.filter((entry) => entry.assignmentConfidence === "inferred_needs_confirmation").length,
  };
}

export function validateEngineeringRoster(roster = ENGINEERING_ROSTER) {
  const errors: string[] = [];
  const corporateEmails = new Set<string>();
  const sourceRows = new Set<number>();
  for (const entry of roster) {
    if (!/^[a-z0-9][a-z0-9.-]*@agoojiye\.com$/.test(entry.corporateEmail)) {
      errors.push(`Adresse AGOOJIYE invalide: ${entry.corporateEmail}`);
    }
    if (corporateEmails.has(entry.corporateEmail)) {
      errors.push(`Adresse AGOOJIYE en doublon: ${entry.corporateEmail}`);
    }
    corporateEmails.add(entry.corporateEmail);
    for (const row of entry.sourceRows) {
      if (sourceRows.has(row)) errors.push(`Ligne source réutilisée: ${row}`);
      sourceRows.add(row);
    }
  }
  if (roster.length !== 34) errors.push(`34 ingénieurs attendus, ${roster.length} reçus`);
  if (!sourceRows.has(6) || !sourceRows.has(36)) {
    errors.push("Le doublon Judicaël des lignes 6 et 36 n'est pas correctement fusionné");
  }
  return { ok: errors.length === 0, errors };
}

export function assertNoOutboundDeliveryArguments(args: string[]) {
  const forbidden = args.find((arg) => /^--(send|notify|email|invite)(=|$)/i.test(arg));
  if (forbidden) {
    throw new Error(
      `Option interdite pendant la préparation des comptes: ${forbidden}. Aucun envoi n'est implémenté par ce provisionneur.`,
    );
  }
}
