listening-port=3478
tls-listening-port=5349

realm=meet.exportunity.net
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=CHANGE_ME_TURN_SECRET

total-quota=200
stale-nonce=600
no-multicast-peers
no-loopback-peers

min-port=49160
max-port=49200

cert=/etc/ssl/certs/turn.pem
pkey=/etc/ssl/private/turn.key
