import type { TenantConfig } from "../types";
import { metModulesDisabled, metModulesEnabled } from "./modules";
import { metThemeTokens } from "./theme";

export const metTenantConfig: TenantConfig = {
  slug: "met",
  brandName: "Maison en Terre",
  tagline: "Briques BTC/CEB, maison modele et livraison chantier",
  primaryDomain: "maisonenterre.com",
  domains: [
    "maisonenterre.com",
    "www.maisonenterre.com",
    "maisonsenterre.com",
    "www.maisonsenterre.com",
  ],
  defaultLocale: "fr",
  uiMode: "industrial",
  categoryPreset: "construction",
  homeMode: "platform",
  homeRedirectTo: "/store",
  storefrontMarketType: "ALL",
  modulesEnabled: metModulesEnabled,
  modulesDisabled: metModulesDisabled,
  themeTokens: metThemeTokens,
  storefrontHero: {
    eyebrow: "Materiaux de construction",
    title: "Construisez avec des materiaux en terre, durables et livrables sur chantier",
    subtitle: "Briques BTC/CEB, maison modele et accompagnement chantier dans une experience claire et francaise.",
    ctaPrimary: { label: "Voir les materiaux", href: "/store" },
    ctaSecondary: { label: "Demander un devis", href: "/devis" },
    backgroundStyle: "from-[#2e1a09] via-[#553018] to-[#7a3e12]",
  },
  storefrontTheme: {
    colors: {
      bg: "#f5efd9",
      surface: "#ffffff",
      text: "#1f2937",
      primary: "#7a3e12",
      accent: "#0f6b4e",
    },
    accent: "#0f6b4e",
    background: "linear-gradient(180deg, #f5efd9 0%, #f0ead4 100%)",
    typography: "Cabin, system-ui, sans-serif",
    heroBanner: {
      gradientFrom: "#2e1a09",
      gradientTo: "#7a3e12",
    },
  },
  marketplaceDefaults: {
    defaultCurrency: "XOF",
    distanceUnit: "km",
    deliveryRadiusKm: 60,
    enabledCategories: [
      "earth-bricks",
      "clay-plaster",
      "lime",
      "lime-plaster",
      "bamboo",
      "natural-insulation",
      "solar-lighting",
      "house-plans",
      "tools-equipment",
      "contractor-services",
    ],
  },
  storefrontIdentity: {
    platformLabel: "Materiaux de construction",
    retailModeLabel: "Materiaux",
    sections: [
      { slug: "earth-bricks", title: "Briques BTC/CEB", subtitle: "Blocs structurels en terre compressee", limit: 24 },
      { slug: "house-plans", title: "Plans de maison", subtitle: "Modeles, guides et inspirations", limit: 24 },
      { slug: "contractors", title: "Reseau chantier", subtitle: "Artisans, equipes et accompagnement", limit: 24 },
      { slug: "tools", title: "Outils & equipements", subtitle: "Kits, outils et logistique chantier", limit: 24 },
    ],
    categoryVisuals: [
      { slug: "earth-bricks", label: "Briques BTC/CEB", icon: "BRK", accent: "#c19a6b", image: "/tenants/met/material-earth-bricks.svg" },
      { slug: "clay-plaster", label: "Enduit terre", icon: "CLY", accent: "#9b6a3b", image: "/tenants/met/material-lime-plaster.svg" },
      { slug: "lime", label: "Chaux", icon: "LIM", accent: "#7a3e12", image: "/tenants/met/material-lime-plaster.svg" },
      { slug: "lime-plaster", label: "Chaux / enduit", icon: "LIM", accent: "#7a3e12", image: "/tenants/met/material-lime-plaster.svg" },
      { slug: "bamboo", label: "Bambou", icon: "BAM", accent: "#6b8e23", image: "/tenants/met/material-bamboo.svg" },
      { slug: "natural-insulation", label: "Isolation naturelle", icon: "INS", accent: "#59753a", image: "/tenants/met/material-bamboo.svg" },
      { slug: "solar-lighting", label: "Eclairage solaire", icon: "SOL", accent: "#0f6b4e", image: "/tenants/met/material-solar-lighting.svg" },
      { slug: "house-plans", label: "Plans de maison", icon: "PLN", accent: "#8b5e34", image: "/tenants/met/material-contractor-services.svg" },
      { slug: "tools-equipment", label: "Outils & equipements", icon: "TLS", accent: "#8b5e34", image: "/tenants/met/material-contractor-services.svg" },
      { slug: "contractor-services", label: "Services chantier", icon: "SVC", accent: "#8b5e34", image: "/tenants/met/material-contractor-services.svg" },
    ],
  },
  assets: {
    logoPath: "/tenants/met/logo.svg",
    faviconPath: "/tenants/met/favicon.svg",
    placeholderProduct: "/tenants/met/placeholder-product.svg",
    heroImages: ["/tenants/met/hero-1.svg"],
  },
};
