import "../env";
import { sendEmailAsAgent } from "../server/lib/mail/sender";
import { db } from "../db";
import { tenants } from "../db/schema";
import { eq } from "drizzle-orm";

const TEST_RECIPIENTS = {
  gmail: process.env.TEST_EMAIL_GMAIL?.split(",") || ["vs+test1@gmail.com", "vs+test2@gmail.com"],
  outlook: process.env.TEST_EMAIL_OUTLOOK?.split(",") || ["vs+test@outlook.com"],
  yahoo: process.env.TEST_EMAIL_YAHOO?.split(",") || ["vs+test@yahoo.com"],
  internal: process.env.TEST_EMAIL_INTERNAL?.split(",") || ["vs@exportunity.net"],
};

type TestCase = {
  tenant: string;
  agent: string;
  type: keyof typeof TEST_RECIPIENTS;
  to: string[];
};

async function runTest(testCase: TestCase) {
  const { tenant: tenantKey, agent: agentKey, type: recipientType, to } = testCase;

  const tenant = await db.query.tenants.findFirst({
    where: eq(tenants.key, tenantKey as any),
  });
  if (!tenant) throw new Error(`Tenant not found: ${tenantKey}`);

  console.log(`\n[TEST] ${tenantKey} → ${agentKey} → ${recipientType} (${to.join(", ")})`);

  const timestamp = new Date().toISOString();
  const testId = `test-${Date.now()}`;

  try {
    const result = await sendEmailAsAgent({
      tenantId: tenant.id,
      agentKey,
      actorType: "system",
      to,
      subject: `[EMAIL ACCEPTANCE TEST] ${tenantKey} → ${recipientType}`,
      textBody: `EMAIL DELIVERY ACCEPTANCE TEST
========================

Test ID: ${testId}
Timestamp: ${timestamp}
Tenant: ${tenantKey}
Agent Key: ${agentKey}
Recipient Type: ${recipientType}
Recipients: ${to.join(", ")}

PURPOSE:
--------
This email verifies that:
1. SPF authentication passes
2. DKIM signature validates
3. DMARC policy aligns
4. Email reaches recipient inbox (not spam)

EXPECTED RESULT:
----------------
If you received this email:
✅ SPF: PASS
✅ DKIM: PASS
✅ DMARC: PASS
✅ Delivery Status: DELIVERED_REMOTE_ACCEPTED

ACTION REQUIRED:
----------------
Reply with "CONFIRMED" to verify receipt.
Check email headers ("Show Original" in Gmail) and confirm SPF/DKIM/DMARC all pass.

---
Generated by Email Acceptance Test Suite
Platform: Agentic Company OS (${tenantKey})
`,
      htmlBody: `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; border-radius: 8px; }
    .content { padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; margin-top: 20px; }
    .test-info { background: #f3f4f6; padding: 15px; border-radius: 6px; margin: 15px 0; }
    .expected { background: #d1fae5; padding: 15px; border-radius: 6px; margin: 15px 0; }
    .action { background: #fef3c7; padding: 15px; border-radius: 6px; margin: 15px 0; }
    code { background: #1f2937; color: #10b981; padding: 2px 6px; border-radius: 3px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📧 Email Delivery Acceptance Test</h1>
    <p>Verifying SPF + DKIM + DMARC Authentication</p>
  </div>

  <div class="content">
    <div class="test-info">
      <h3>Test Information</h3>
      <ul>
        <li><strong>Test ID:</strong> <code>${testId}</code></li>
        <li><strong>Timestamp:</strong> ${timestamp}</li>
        <li><strong>Tenant:</strong> ${tenantKey}</li>
        <li><strong>Agent:</strong> ${agentKey}</li>
        <li><strong>Recipient Type:</strong> ${recipientType}</li>
        <li><strong>Recipients:</strong> ${to.join(", ")}</li>
      </ul>
    </div>

    <div class="expected">
      <h3>✅ Expected Result</h3>
      <p>If this email was delivered successfully:</p>
      <ul>
        <li>✅ <strong>SPF:</strong> PASS</li>
        <li>✅ <strong>DKIM:</strong> PASS</li>
        <li>✅ <strong>DMARC:</strong> PASS</li>
        <li>✅ <strong>Status:</strong> DELIVERED_REMOTE_ACCEPTED</li>
      </ul>
    </div>

    <div class="action">
      <h3>⚠️ Action Required</h3>
      <ol>
        <li>Reply with <strong>"CONFIRMED"</strong> to verify receipt</li>
        <li>Check email headers (Gmail: Show Original → look for <code>ARC-Authentication-Results</code>)</li>
        <li>Confirm all authentication checks passed</li>
      </ol>
    </div>
  </div>

  <footer style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
    <p>Generated by Email Acceptance Test Suite<br>
    Platform: Agentic Company OS (${tenantKey})</p>
  </footer>
</body>
</html>`,
      bypassApproval: true,
      correlationId: testId,
    });

    console.log("[RESULT]", JSON.stringify(result, null, 2));
    return {
      ...testCase,
      ok: result.ok,
      status: result.message?.status || "unknown",
      messageId: result.message?.messageId || null,
      queueId: result.message?.queueId || null,
    };
  } catch (err: any) {
    console.error("[ERROR]", err.message);
    return {
      ...testCase,
      ok: false,
      status: "ERROR",
      error: err.message,
    };
  }
}

async function main() {
  console.log("========================================");
  console.log("EMAIL ACCEPTANCE TEST SUITE");
  console.log("========================================\n");

  const tests: TestCase[] = [
    { tenant: "bdo", agent: "diego_alvarez", type: "gmail", to: TEST_RECIPIENTS.gmail },
    { tenant: "bdo", agent: "samuel_mensah", type: "outlook", to: TEST_RECIPIENTS.outlook },
    { tenant: "exportunity", agent: "chairman", type: "yahoo", to: TEST_RECIPIENTS.yahoo },
    { tenant: "exportunity", agent: "cfo", type: "internal", to: TEST_RECIPIENTS.internal },
  ];

  const results = [];
  for (const test of tests) {
    const result = await runTest(test);
    results.push(result);
    await new Promise((resolve) => setTimeout(resolve, 2000)); // Rate limit
  }

  console.log("\n========================================");
  console.log("ACCEPTANCE TEST SUMMARY");
  console.log("========================================\n");
  console.table(results);

  const passed = results.filter((r) => r.ok).length;
  const total = results.length;

  console.log(`\n📊 Results: ${passed}/${total} passed`);

  if (passed === total) {
    console.log("\n✅ ALL TESTS PASSED - Email delivery is OPERATIONAL\n");
    process.exit(0);
  } else {
    console.log("\n❌ SOME TESTS FAILED - Review errors above\n");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("[email-acceptance-tests] Fatal error:", err);
  process.exit(1);
});
