import fs from "fs/promises";
import path from "path";

const APP_FILE = path.resolve(process.cwd(), "client/src/App.tsx");
const OUTPUT_FILE = path.resolve(process.cwd(), "client/src/navigation/routes.generated.ts");

function normalizePath(input: string) {
  const value = String(input || "").trim();
  if (!value.startsWith("/")) return "";
  const [withoutQuery] = value.split(/[?#]/);
  const normalized = withoutQuery.replace(/\/+$/, "");
  return normalized || "/";
}

async function main() {
  const source = await fs.readFile(APP_FILE, "utf8");
  const routeRegex = /<Route\s+path="([^"]+)"/g;
  const discovered: string[] = [];
  let match: RegExpExecArray | null = null;

  while ((match = routeRegex.exec(source)) !== null) {
    const pathValue = normalizePath(match[1] || "");
    if (!pathValue) continue;
    discovered.push(pathValue);
  }

  const uniqueSorted = Array.from(new Set(discovered)).sort((a, b) => a.localeCompare(b));
  const content = `// AUTO-GENERATED by scripts/generate-nav-routes.ts\n// Source: client/src/App.tsx <Route path=\"...\">\n\nexport const APP_ROUTE_PATHS = ${JSON.stringify(uniqueSorted, null, 2)} as const;\n`;

  try {
    const existing = await fs.readFile(OUTPUT_FILE, "utf8");
    if (existing === content) {
      console.log(`[generate-nav-routes] up to date with ${uniqueSorted.length} routes`);
      return;
    }
  } catch {
    // The first generation run creates the file below.
  }

  await fs.writeFile(OUTPUT_FILE, content, "utf8");
  console.log(`[generate-nav-routes] wrote ${uniqueSorted.length} routes to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

main().catch((error) => {
  console.error("[generate-nav-routes] failed:", error?.message || error);
  process.exitCode = 1;
});

